# -*- mode: ruby -*-
# vi: set ft=ruby :

# -*- mode: ruby -*-
# vi: set ft=ruby :
  
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "172.168.10.104"
  config.vm.hostname = "rancher"

  config.vm.provider "virtualbox" do |vb|
     vb.name = "rancher"
     vb.cpus = 2
     vb.memory = "2048"
  end
   
  # config.vm.provision "shell", path: "./../install-docker-kube.sh"

  config.vm.provision "shell", inline: <<-SHELL
  
    echo "root password"
    echo "123" | passwd --stdin root
    sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
    systemctl reload sshd
    

cat >>/etc/hosts<<EOF
172.168.10.100 master
172.168.10.101 worker1
172.168.10.102 worker2
172.168.10.103 worker3
172.168.10.104 rancher 