apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1 
  namespace: testbed
  labels:
    app: pv1
spec:
  capacity:
    storage: 10Gi 
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: standar 
  nfs:
    path: /data/image
    server: 172.168.10.102