apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: testbed
  name: pvc1 
spec:
  resources:
    requests:
      storage: 1Gi 
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany 
  storageClassName: standar
  selector:
    matchLabels:
      app: pv1